### ISSUE TITLE
testground-dashboards are not part of infra repo

### ISSUE THREAD

**Issue by nonsense** [testground/infra#5]
The symlink from the install scripts is broken right now.

I would have just copied them over, but I imagine we want to use the dashboards with other runners as well, and they don't live in this repo.

@coryschwartz shall we just create `dashboards` repo, or maintain a copy of in both `testground/infra` and wherever the rest of the runners would live?

**Comment by coryschwartz** [comment]
Right now only the redis dashboard is useful, with the pushgateway now unused. Depending on the way the influx solution is implemented we may or may not need dashboards applied like this (locally, in the cluster, I mean) 

I merged your PR, closing.
